[project]
name = 'styx'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.sbtc-token'

[[project.requirements]]
contract_id = 'STTWD9SPRQVD3P733V89SV0P8RZRZNQADG034F0A.faktory-trait-v1'

[[project.requirements]]
contract_id = 'ST1Q9YZ2NY4KVBB08E005HAK3FSM8S3RX2WARP9Q1.aibtc-agent-account-traits'

[[project.requirements]]
contract_id = 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.clarity-bitcoin-lib-v7'

[[project.requirements]]
contract_id = 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.bitcoin-helper-wtx-v2'

[[project.requirements]]
contract_id = 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.bitcoin-helper-v2'

[[project.requirements]]
contract_id = 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.bitcoin-helper-wtx-v1'

[[project.requirements]]
contract_id = 'STV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RJ5XDY2.faktory-dex-trait-v21'

[[project.requirements]]
contract_id = 'STTWD9SPRQVD3P733V89SV0P8RZRZNQADG034F0A.xyk-pool-trait-v-1-2'

[[project.requirements]]
contract_id = 'STTWD9SPRQVD3P733V89SV0P8RZRZNQADG034F0A.xyk-core-v-1-2'

[[project.requirements]]
contract_id = 'ST29D6YMDNAKN1P045T6Z817RTE1AC0JAAAG2EQZZ.prelaunch-faktory-trait'

[contracts.agent-account-registry]
path = 'contracts/btc2aibtc/btc2aibtc-prelaunch/agent-account-registry.clar'
clarity_version = 3
epoch = '3.1'

[contracts.pre-trait-final2]
path = 'contracts/btc2aibtc/btc2aibtc-prelaunch/pre-trait-final2.clar'
clarity_version = 3
epoch = '3.1'

[contracts.btc2aibtc-simul]
path = 'contracts/btc2aibtc/btc2aibtc-prelaunch/btc2sbtc-simul-testnet.clar'
clarity_version = 3
epoch = '3.1'

[contracts.an-agent]
path = 'contracts/btc2aibtc/btc2aibtc-prelaunch/an-agent.clar'
clarity_version = 3
epoch = '3.1'

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.testnet.hiro.so'
